datasource:
  url: ${DBMS_CONNECTION:jdbc:mysql://mysql.railway.internal:5923/railway}
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: ${DBMS_USERNAME:root}
  password: ${DBMS_PASSWORD:vqaApL1MIVVpmDAnnSZ0IsSnizXyIhRB}