datasource:
  url: ${DBMS_CONNECTION:jdbc:mysql://crossover.proxy.rlwy.net:26696/railway}
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: ${DBMS_USERNAME:root}
  password: ${DBMS_PASSWORD:CzflGHKGRVTMEZIhcOmHPogEiZgBvgKo}