global:
  scrape_interval: 15s  # Mỗi 15s lấy dữ liệu từ app

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/springboot/api/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
